# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38b7ffb1e643ec73a53b6195fadeaeb9ec577ab401f2dbbbb1fc1ef5f870343628e9102f361c7831c02392a3f92c1c2f1fcacfbfc5f2068000e44892866ea4a6

test:
  secret_key_base: 48c301aefa129c48152dc72878d64ba7d41b3bbe9e537294a3e696761f3b03bb002028902ce4bc8bbecb85a720b78536ffb1f304ac87fa2a4bd0f24e683e3d67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
